# Generated by Django 3.2.4 on 2024-08-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_remove_transactions_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
