# Generated by Django 3.2.4 on 2024-08-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmers', '0002_delete_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('isActive', models.BooleanField(default=False)),
                ('isStaff', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Basic'), (1, 'Pro')], default=0)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, unique=True)),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_type', models.IntegerField(choices=[(0, 'Farmer'), (1, 'Business')], default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmers.farmer')),
            ],
        ),
    ]
