# Generated by Django 3.2.4 on 2024-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0003_account_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='isActive',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='isStaff',
            field=models.IntegerField(default=False),
        ),
    ]
