# Generated by Django 3.2.4 on 2024-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0004_auto_20240802_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='status',
            new_name='plan',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
