# Generated by Django 3.2.4 on 2024-08-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0005_auto_20240802_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Location',
            new_name='location',
        ),
    ]
